### PR TITLE
Issue#50 - Padding-top applied to container instead of :host element

### PR DESCRIPTION
**Pull request by n4gashi**
More info here : https://github.com/GoogleWebComponents/google-youtube/issues/50

### CODE REVIEW

**Comment by n4gashi** [comment]
I signed it!

**Comment by jeffposnick** [comment]
Thanks for the contribution! This looks good to me, but @robdodson wrote the code for `fluid`, and I wouldn't mind him looking over this change as well.

**Comment by n4gashi** [comment]
Yeah, no problem, double-checking is always better ;)

**Comment by addyosmani** [comment]
This change LGTM. Merging.

**Pull request merged**
